human_samples:
  h-ECI-0008: data/human/h-ECI-0008.fasta
  h-ECI-0015: data/human/h-ECI-0015.fasta
  h-ECI-0123: data/human/h-ECI-0123.fasta
  h-ECI-0132: data/human/h-ECI-0132.fasta
  h-ECI-0217: data/human/h-ECI-0217.fasta
  h-ECI-0249: data/human/h-ECI-0249.fasta
  h-ECI-0258: data/human/h-ECI-0258.fasta
  h-ECI-0270: data/human/h-ECI-0270.fasta
  h-ECI-0272: data/human/h-ECI-0272.fasta
  h-ECI-0351: data/human/h-ECI-0351.fasta
  h-ECI-0357: data/human/h-ECI-0357.fasta
  h-ECI-0497: data/human/h-ECI-0497.fasta
  h-ECI-0504: data/human/h-ECI-0504.fasta
  h-ECI-0855: data/human/h-ECI-0855.fasta
  h-ECI-0857: data/human/h-ECI-0857.fasta
  h-ECI-2859: data/human/h-ECI-0857.fasta

bovine_samples:
  b-ECI-0715: data/bovine/b-ECI-0715.fasta
  b-ECI-0715: data/bovine/b-ECI-0715.fasta
  b-ECI-1364: data/bovine/b-ECI-1364.fasta
  b-ECI-1437: data/bovine/b-ECI-1437.fasta
  b-ECI-1717: data/bovine/b-ECI-1717.fasta
  b-ECI-1830: data/bovine/b-ECI-1830.fasta
  b-ECI-1907: data/bovine/b-ECI-1907.fasta
  b-ECI-1908: data/bovine/b-ECI-1908.fasta
  b-ECI-1909: data/bovine/b-ECI-1909.fasta
  b-ECI-1910: data/bovine/b-ECI-1910.fasta
  b-ECI-1911: data/bovine/b-ECI-1911.fasta
  b-ECI-1912: data/bovine/b-ECI-1912.fasta
  b-ECI-2570: data/bovine/b-ECI-2570.fasta
  b-ECI-2571: data/bovine/b-ECI-2571.fasta
  b-ECI-2573: data/bovine/b-ECI-2573.fasta
  b-ECI-2578: data/bovine/b-ECI-2578.fasta
  b-ECI-2583: data/bovine/b-ECI-2583.fasta
  b-ECI-2591: data/bovine/b-ECI-2591.fasta