
human_samples:
  ECI-0008: data/human/ECI-0008.fasta
  ECI-0015: data/human/ECI-0015.fasta
  ECI-0123: data/human/ECI-0123.fasta
  ECI-0132: data/human/ECI-0132.fasta
  ECI-0217: data/human/ECI-0217.fasta
  ECI-0249: data/human/ECI-0249.fasta
  ECI-0258: data/human/ECI-0258.fasta
  ECI-0270: data/human/ECI-0270.fasta
  ECI-0272: data/human/ECI-0272.fasta
  ECI-0351: data/human/ECI-0351.fasta
  ECI-0357: data/human/ECI-0357.fasta
  ECI-0497: data/human/ECI-0497.fasta
  ECI-0504: data/human/ECI-0504.fasta
  ECI-0855: data/human/ECI-0855.fasta
  ECI-0857: data/human/ECI-0857.fasta
  ECI-2859: data/human/ECI-0857.fasta

bovine_samples:
  ECI-0715: data/bovine/ECI-0715.fasta
  ECI-1364: data/bovine/ECI-1364.fasta
  ECI-1437: data/bovine/ECI-1437.fasta
  ECI-1717: data/bovine/ECI-1717.fasta
  ECI-1830: data/bovine/ECI-1830.fasta
  ECI-1907: data/bovine/ECI-1907.fasta
  ECI-1908: data/bovine/ECI-1908.fasta
  ECI-1909: data/bovine/ECI-1909.fasta
  ECI-1910: data/bovine/ECI-1910.fasta
  ECI-1911: data/bovine/ECI-1911.fasta
  ECI-1912: data/bovine/ECI-1912.fasta
  ECI-2570: data/bovine/ECI-2570.fasta
  ECI-2571: data/bovine/ECI-2571.fasta
  ECI-2573: data/bovine/ECI-2573.fasta
  ECI-2578: data/bovine/ECI-2578.fasta
  ECI-2583: data/bovine/ECI-2583.fasta
  ECI-2591: data/bovine/ECI-2591.fasta